dist: xenial

language: java

jdk:
- openjdk8
 
services:
  # -----------------------------------------------------
  # Start up xvfb service for SWT bot GUI tests
  # -----------------------------------------------------
  - xvfb 

cache:
  directories:
  - $HOME/.m2

install:
- true

stages:
# ------------------------------------
# Just one stage, multiple stages 
# with maven overcomplicate the things
# ------------------------------------
- name: clean-install

env:
- CODECOV_TOKEN: 1ff41125-242d-4ee6-ad92-b4e0d938bf5a
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
